botbackend/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pack/list/', views.packlist, name='pack_list'),
    path('path/create/', views.PackCreateView.as_view(), name='pack_create'),
    path('path/<int:pk>/edit/', views.PackUpdateView.as_view(), name='pack_edit'),
    path('path/<int:pk>/delete/', views.PackDeleteView.as_view() , name='pack_del'),
    path('card/list/', views.cardlist, name='card_list_all'),
    path('card/create/', views.CardCreateView.as_view(), name='card_create'),
    path('card/<int:pk>/edit/', views.CardUpdateView.as_view(), name='card_edit' ),
    path('card/<int:pk>/delete/', views.CardDeleteView.as_view() , name='card_del'),
    path('steps/list/', views.stepslist, name='steps_list'),
    path('steps/create/', views.StepsCreateView.as_view() , name='steps_create'),
    path('steps/<int:pk>/edit/', views.StepsUpdateView.as_view(), name='steps_edit' ),
    path('steps/<int:pk>/delete/', views.StepsDeleteView.as_view() , name='steps_del'),
    path('chatusers/list/', views.chatuserlist, name='chatuser_list'),
    path('chatuser/<int:pk>/activate/', views.chatuseractivate, name='chatuser_activate'),
    path('chatuser/<int:pk>/deactivate/', views.chatuserdeactivate, name='chatuser_deactivate'),
    path('messages/showparams/', views.pagenerator , name='messages_pagenerator'),
    path('messages/create/', views.generateimg , name='messages_createimg'),
]

cupidongame/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.homepage, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('botback/', include('botbackend.urls')),
]

botbackend/models.py
from django.db import models
from django.urls import reverse

class Chatusers(models.Model):
    chatid = models.TextField(verbose_name='Идентификатор чата')
    name = models.CharField(max_length=110, verbose_name='Имя пользователя', default=None, blank=True, null=True)
    isactive = models.BooleanField(verbose_name='Запись активна', default=False)
    curstep = models.ForeignKey('Pack', verbose_name='Текущая колода', on_delete=models.SET_DEFAULT, default=None, blank=True, null=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
            ]
    
    def __str__(self) -> str:
        return f'{self.name} ({self.chatid})'
    
    def get_absolute_url(self): 
        return reverse('chatuser_list')

class Pack(models.Model):
    class Packtypes(models.TextChoices):
        TXT = 'TXT', 'Текстовая колода'
        IMG = 'IMG', 'Колода с рисунками'
        CTJ = 'CTJ', 'Текстовая колода, формирующая рисунок'

    order = models.IntegerField(verbose_name='Номер вывода')
    name = models.CharField(max_length=50, verbose_name='Имя колоды', unique=True)
    packtype = models.CharField(max_length=3, choices=Packtypes.choices, default=Packtypes.TXT, verbose_name='Тип колоды')
    
    class Meta:
        ordering = ['order']
        indexes = [
            models.Index(fields=['name']),
            ]
    
    def __str__(self) -> str:
        return f'{self.order} {self.name}'
    
    def get_absolute_url(self): 
        return reverse('pack_list')

class Card(models.Model):
    pack = models.ForeignKey('Pack', verbose_name='Колода', on_delete=models.CASCADE, blank=False)
    number = models.CharField(max_length=3, verbose_name='Отображаемое число')
    cardtext = models.TextField(verbose_name='Текст или ссылка на файл')

    class Meta:
        ordering = ['pack', 'number']

    def __str__(self) -> str:
        return f'{self.number}: {self.cardtext}'

    def get_absolute_url(self): 
        return reverse('card_list_all')

class Steplist(models.Model):
    stepname = models.CharField(max_length=50, verbose_name='Имя шага')
    funcname = models.CharField(max_length=50, verbose_name='Функция теущего шага')

    def __str__(self) -> str:
        return self.stepname

    def get_absolute_url(self): 
        return reverse('steps_list')

#class 

cupidongame/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

cupidongame/templates/base.html
{% load static %}
{% load bootstrap5 %}
{% load curmenu %}
<!DOCTYPE html> 
<html lang="ru">
    <head>
        <meta charset="UTF-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Управление чат-ботом{% endblock %}</title> 
        <link rel="shortcut icon" href="{% static 'jpg/favicon.png' %}" type="image/x-icon">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> 
    </head>
    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark" >
            <div class="col-3">
                <a class="navbar-brand" href="{% url 'home' %}">Управление чат-ботом "Купидон"</a>
            </div>
            <div class="col-7"></div>    
            <div class="col-2 text-end">
                {% if user.is_authenticated %}                
                        <a class="btn btn-secondary" href="{% url 'logout' %}" role="button">Выйти</a>
                        {% else %}
                        <a class="btn btn-primary" href="{% url 'login' %}" role="button">Авторизация</a>
                {% endif %}
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
              <div class="col-2">{% showleftmenu %}</div>
              <main class="col">
                 {% block content %}{% endblock content %}
              </main>
            </div>
          </div>

        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

cupidongame/templates/card_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Создать новую карту{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Создание новой карты</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Создать</button>
        <a href="{% url 'card_list_all' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/card_del.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Удаление карты{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Удалить карту "{{ cardtext }}"?</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'pack_list' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/card_edit.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Редактирование карты{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Изменить карту</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Изменить</button>
        <a href="{% url 'card_list_all' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/card_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% load icon %}
{% block title %}Карты{% endblock %}
{% block content %}
    {% if user.is_staff %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-1 text-start">
                    <h3>Карты</h3>
                </div>
                <div class="col-2 text-start">
                    <a href="{% url 'card_create' %}" class="btn btn-primary ml-2">Создать карту</a>
                </div>
                <div class="col-9 text-start"></div>
            </div>
            <div class="row bg-secondary">
                <div class="col-2 border text-light">Колода</div>
                <div class="col border text-light">Отображаемый номер</div>
                <div class="col border text-light">Текст или путь к файлу</div>
                <div class="col-1 border text-light"></div>
            </div>
            {% for card in cards %}
                <div class="row">
                    <div class="col-2 border bg-secondary-subtle">{{ card.pack }}</div>
                    <div class="col border bg-secondary-subtle">{{ card.number }}</div>
                    <div class="col border bg-secondary-subtle">{{ card.cardtext }}</div>
                    <div class="col-1 border bg-secondary-subtle">
                        <a href="{% url 'card_edit' card.pk %}">{% icon "edit-3" %}</a>
                        <a href="{% url 'card_del' card.pk %}" title="Удалить карту">{% icon "trash" %}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container-fluid">
            <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
        </div>
    {% endif %}
{% endblock %}

cupidongame/templates/messagefinish.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Начальная страница{% endblock %}
{% block content %}
<div class="container">
  <div class="row text-center">
    <h4>Создание изображений завершено.</h4>
  </div>
  {% if user.is_authenticated %}
  {% else %}
  <div class="row text-center">
    <h4>Для продолжения работы пожалуйста авторизуйтесь.</h4>
  </div>
  {% endif %}
</div>


{% endblock %}

cupidongame/templates/messages.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% load icon %}
{% block title %}Параметры генерации сообщений{% endblock %}
{% block content %}
    {% if user.is_staff %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-6 text-start">
                    <h3>Параметры генерации сообщений</h3>
                </div>
                <div class="col-2 text-start">
                    
                </div>
                <div class="col-7 text-start"></div>
            </div>

            {% for pname, pvalue in pagenparams.items %}
            <div class = "row">
                <div class="col-4 border bg-secondary-subtle">{{pname}}</div>
                <div class="col border bg-secondary-subtle">{{pvalue}}</div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-6 text-start">
                    <h3>Операции</h3>
                </div>
                <div class="col-2 text-start">
                    
                </div>
                <div class="col-7 text-start"></div>
            </div>
            <div class = "row">
                <div class="col-4"><a class="btn btn-primary" href="{% url 'messages_createimg' %}" role="button">
                    Сформировать изображения на основе текста
                    </a>
                </div>
                <div class="col"></div>
            </div>
        </div>
    {% else %}
        <div class="container-fluid">
            <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
        </div>
    {% endif %}
{% endblock %}

cupidongame/templates/pack_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Создать новую колоду{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Создание новой колоды</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Создать</button>
        <a href="{% url 'pack_list' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/pack_edit.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Редактирование колоды{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Изменить колоду</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Изменить</button>
        <a href="{% url 'pack_list' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/pack_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% load icon %}
{% block title %}Колоды{% endblock %}
{% block content %}
    {% if user.is_staff %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-1 text-start">
                    <h3>Колоды</h3>
                </div>
                <div class="col-2 text-start">
                    <a href="{% url 'pack_create' %}" class="btn btn-primary ml-2">Создать колоду</a>
                </div>
                <div class="col-9 text-start">
                    
                </div>
            </div>
            <div class="row bg-secondary">
                <div class="col-2 border text-light">Номер вывода</div>
                <div class="col border text-light">Название колоды</div>
                <div class="col border text-light">Тип колоды</div>
                <div class="col-1 border text-light"></div>
            </div>
            {% for pack in packs %}
                <div class="row">
                    <div class="col-2 border bg-secondary-subtle">{{ pack.order }}</div>
                    <div class="col border bg-secondary-subtle">{{ pack.name }}</div>
                    <div class="col border bg-secondary-subtle">{{ pack.get_packtype_display }}</div>
                    <div class="col-1 border bg-secondary-subtle">
                        <a href="{% url 'pack_edit' pack.pk %}">{% icon "edit-3" %}</a>
                        <a href="{% url 'pack_del' pack.pk %}" title="Удалить колоду">{% icon "trash" %}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container-fluid">
            <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
        </div>
    {% endif %}
{% endblock %}

cupidongame/templates/steps_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Создать новый шаг{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Создание нового шага</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Создать</button>
        <a href="{% url 'steps_list' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/steps_del.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Удаление функции{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Удалить шаг {{stepname}}?</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'steps_list' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/steps_edit.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Редактирование функции{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <h1>Изменить функцию</h1>
    <form action="" method="post">{% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">Изменить</button>
        <a href="{% url 'steps_list' %}" class="btn btn-secondary ml-2">Отмена</a>
        {% endbuttons %}
    </form>
{% else %}
    <div class="container-fluid">
        <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
    </div>
{% endif %}
{% endblock %}

cupidongame/templates/steps_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% load icon %}
{% block title %}Функции шагов{% endblock %}
{% block content %}
    {% if user.is_staff %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-3 text-start">
                    <h3>Список функций шагов</h3>
                </div>
                <div class="col-2 text-start">
                    <a href="{% url 'steps_create' %}" class="btn btn-primary ml-2">Создать шаг</a>
                </div>
                <div class="col-7 text-start"></div>
            </div>
            <div class="row bg-secondary">
                <div class="col-2 border text-light">Название шага</div>
                <div class="col border text-light">Функция шага</div>
                <div class="col-1 border text-light"></div>
            </div>
            {% for step in steps %}
                <div class="row">
                    <div class="col border bg-secondary-subtle">{{ step.stepname }}</div>
                    <div class="col border bg-secondary-subtle">{{ step.funcname }}</div>
                    <div class="col-1 border bg-secondary-subtle">
                        <a href="{% url 'steps_edit' step.pk %}">{% icon "edit-3" %}</a>
                        <a href="{% url 'steps_del' step.pk %}">{% icon "trash" %}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="container-fluid">
            <div class="row bg-danger">Доступ к данной странице запрещен. Пожалуйста обратитесь к администратору для получения доступа.</div>
        </div>
    {% endif %}
{% endblock %}